services:
  dreamy_mahavira:
    image: mysql:latest

    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - isganet
    restart: unless-stopped

  myservice:
    image: my-app:latest
    ports:
      - 8088:8083
    networks:
      - isganet
    depends_on:
      - dreamy_mahavira
    restart: on-failure
networks:
  isganet: { }